### ISSUE TITLE
terminal.d compile error

### ISSUE THREAD

**Issue by quickfur** [adamdruppe/arsd#211]
Compiled with `-version=with_eventloop`:
````
arsd/terminal.d(1711): Error: undefined identifier `timeout`, did you mean alias `time_t`?
````

Appears to have been caused by commit b7ad04afd.

**Comment by adamdruppe** [comment]
oops i pushed some unfinished thing

i prolly just pushed an unfinished minigui thing now too but meh

try it now

**Comment by quickfur** [comment]
Yep that did it, thanks!
